services:
  dikidi_frontend:
    image: dikidi_frontend
    container_name: dikidi_frontend
    restart: always
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./env-config.js:/usr/share/nginx/html/static/env-config.js
    ports:
      - 80:80
      - 443:443
    networks:
      - dikidi
    environment:
    #   - NGINX_SERVER_NAME=your_domain.com
      - NGINX_INTERNAL_API_URL=http://89.110.91.103:5000
    #   - NGINX_SECURE=false
    #   - NGINX_SSL_CERTIFICATE=/etc/nginx/ssl/nginx.crt
    #   - NGINX_SSL_CERTIFICATE_KEY=/etc/nginx/ssl/nginx.key
    # volumes:
    #   - ./ssl:/etc/nginx/ssl

networks:
  dikidi:
    # external: true
    name: dikidi